### PR TITLE
Use PlotlyBase to generate the figure in the Graph example

### PR DESCRIPTION
**Pull request by mzaffalon**
... and remove unused RDataset

### CODE REVIEW

**Comment by mzaffalon** [comment]
Apologies if leaving the example using plotly.js was intentional.

**Comment by mzaffalon** [comment]
Sorry for pushing to master. Should I make a new PR to a branch?

**Comment by sglyon** [comment]
Thanks for the contribution!

This was implemented over in https://github.com/plotly/dash-julia-docs/pull/20/files#diff-7de2c011c0c1fd67eb964ad187743ce12f7ab836368f145f442ba4bc9eaf96f4

**Comment by mzaffalon** [comment]
Yes, I saw your PR after I submitted mine. Thank you for maintaining the documentation in sync with the code.

If I can use the opportunity to ask one question: how is the documentation compiled?

**Comment by sglyon** [comment]
Good question, which documentation? Right now there are kinda three sets:

- These docs here: they are run as a live dash app by running the `run.jl` file
- The PlotlyJS.jl docs: these belong in the PlotlyJS.jl repo and are deployed to github pages via this github action: https://github.com/JuliaPlots/PlotlyJS.jl/blob/master/.github/workflows/deploy_docs.yml
- The docs at https://plotly.com/julia/: The docs there are being totally overhauled to be brought up to speed with what you'd find at https://plotly.com/python/. The source is here https://github.com/plotly/plotlyjs.jl-docs and these should be deployed very soon! The build happens with this Julia script: https://github.com/plotly/plotlyjs.jl-docs/blob/master/make.jl

**Comment by mzaffalon** [comment]
Thank you! I meant the `dash-julia-docs`.

~~I see that `DashUserGuideComponents` and `DashDocs` are needed, which are not in the public registry.~~ They are included in this repo. In case I wanted to submit a PR, I would like to make sure that the PR is correct.

**Comment by mzaffalon** [comment]
If I start the Dash app, navigate to http://127.0.0.1:8050/dash-core-components, click on graph on the RHS navigation table and then again on the link Graph (see snapshot below), I reach http://127.0.0.1:8050/dash_core_components/graph but the page displayed is the same as the one I see at http://127.0.0.1:8050/

image

**Pull request closed without merging**
